### PR TITLE
Dependency Upgrade

### PR DESCRIPTION
**Pull request by kevinthedang**
## Changes
* Upgraded `ollama-js` dependency to latest.
* Upgraded other development dependencies.
* Fixed issue with tests not running at root level for PRs.

## Notes
* This runs fine locally with `npm run client`

### CODE REVIEW

**Comment by JT2M0L3Y** [comment]
Yeah, I assess what we currently had (compared to the forked repo) and I think we are good either way.

**Review by JT2M0L3Y — APPROVED** [review]
no comment

**Comment by kevinthedang** [comment]
With the forked repo I saw, it was a little behind on fixes and dependencies. I just do this every now and then.

**Comment by kevinthedang** [comment]
Will also reference #73

**Pull request merged**
