### PR TITLE
Auto-Generate Config

### PR DESCRIPTION
**Pull request by kevinthedang**
## Added
* `config.json` file is now generated if it is missing setting the default `message-style` to embedded.

## Notes
* Added to the goals in the main readme.
* Updated a job step to the correct name based on the command

image

### CODE REVIEW

**Review by JT2M0L3Y — APPROVED** [review]
So... default config for message style?

**Comment by kevinthedang** [comment]
@JT2M0L3Y Kinda? I just put something there for now to generate it, I could set something for everything if that works better?

**Comment by JT2M0L3Y** [comment]
Well, it looks (from the local testing you were doing in discord last night) that the bot was missing an initial configuration for a user preference. I would imagine the bot would prefer an initial configuration. However, this is in a good state for now.

**Comment by kevinthedang** [comment]
I suppose we could generate a message to the users of what configurations are missing. In this case, it was just message-style as that is the only config we've really implemented.

**Review by JT2M0L3Y — APPROVED** [review]
This looks good.

**Pull request merged**
